extends: airbnb

globals:
  document: true
  window: true
  React: true

rules:
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  max-len: [2, 160, {"ignoreUrls": true}]
  class-methods-use-this: 0
