extends: airbnb

globals:
  document: true
  window: true
  React: true
  App: true
  ActionCable: true
  test: true
  it: true
  expect: true
  jest: true
  describe: true
  beforeEach: true
  afterEach: true

rules:
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types:
    - 2
    - forbid:
      - 'array'
      - 'any'
  max-len: [2, 160, {"ignoreUrls": true}]
  class-methods-use-this: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/label-has-for: 0
