inherit_gem:
  deka_eiwakun: "config/rubocop.yml"

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - app/**/*.rb
    - config/**/*.rb
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'spec/factories/*.rb'
    - db/*

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Style/RescueStandardError:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
