sudo: false
language: ruby
rvm:
  - 2.4.2
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

services:
  - postgresql
  - redis-server

bundler_args: "--without development --deployment"

before_install:
  - nvm install 8.11.1
  - npm config set spin false
  - npm install -g yarn
  - npm install -g codecov

install:
  - bundle install
  - node -v
  - bin/yarn

before_script:
  - cp -f config/database.travis.yml config/database.yml
  - cp -f config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - yarn run test
  - bundle exec rubocop
  - bundle exec rspec spec
