version: '2'
services:
  db:
    restart: always
    image: postgres:alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./vendor/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
  redis:
    restart: always
    image: redis:alpine
    ports:
      - '127.0.0.1:6379:6379'
